/**
 * Capability Providers for MCP LSP Driver SDK
 *
 * The Plugin Developer provides an implementation of IdeCapabilities.
 * The SDK exposes tools based on which optional providers are defined.
 *
 * Note: All inputs here use ExactPosition. The SDK handles the
 * Fuzzy -> Exact conversion before calling these.
 */

import type {
  FileAccessProvider,
  UserInteractionProvider,
} from './interfaces.js'
import type {
  CodeSnippet,
  Diagnostic,
  DocumentSymbol,
  ExactPosition,
  UnifiedUri,
} from './types.js'

// ============================================================================
// LSP Capability Providers
// ============================================================================

/**
 * Provides go-to-definition functionality.
 */
export interface DefinitionProvider {
  /**
   * Returns definition location reading strictly from disk context.
   *
   * @param uri - The URI of the file
   * @param position - The exact position to find the definition for
   * @returns Array of code snippets representing definition locations
   */
  provideDefinition(
    uri: UnifiedUri,
    position: ExactPosition,
  ): Promise<CodeSnippet[]>
}

/**
 * Provides find-references functionality.
 */
export interface ReferencesProvider {
  /**
   * Finds all references to the symbol at the given position.
   *
   * @param uri - The URI of the file
   * @param position - The exact position to find references for
   * @returns Array of code snippets representing reference locations
   */
  provideReferences(
    uri: UnifiedUri,
    position: ExactPosition,
  ): Promise<CodeSnippet[]>
}

/**
 * Provides call hierarchy functionality.
 */
export interface HierarchyProvider {
  /**
   * Provides call hierarchy information for the symbol at the given position.
   *
   * @param uri - The URI of the file
   * @param position - The exact position to get call hierarchy for
   * @param direction - Whether to get incoming or outgoing calls
   * @returns Array of code snippets representing call hierarchy items
   */
  provideCallHierarchy(
    uri: UnifiedUri,
    position: ExactPosition,
    direction: 'incoming' | 'outgoing',
  ): Promise<CodeSnippet[]>
}

/**
 * Provides diagnostics (errors, warnings) for a file.
 */
export interface DiagnosticsProvider {
  /**
   * Gets diagnostics for a file.
   *
   * @param uri - The URI of the file
   * @returns Array of diagnostics for the file
   */
  provideDiagnostics(uri: UnifiedUri): Promise<Diagnostic[]>

  /**
   * Gets diagnostics for all files in the workspace.
   * If not provided, the workspace diagnostics resource will not be available.
   *
   * @returns Array of diagnostics for all files in the workspace
   */
  getWorkspaceDiagnostics?(): Promise<Diagnostic[]>
}

/**
 * Provides document outline (symbols) for a file.
 */
export interface OutlineProvider {
  /**
   * Gets the document symbols (outline) for a file.
   *
   * @param uri - The URI of the file
   * @returns Array of document symbols representing the file's outline
   */
  provideDocumentSymbols(uri: UnifiedUri): Promise<DocumentSymbol[]>
}

/**
 * Provides filesystem access with git-ignore support.
 */
export interface FilesystemProvider {
  /**
   * Gets the file tree for a directory, excluding git-ignored files.
   *
   * @param folderPath - The path to the folder to read
   * @returns Array of file/folder paths in the directory tree
   */
  getFileTree(folderPath: string): Promise<string[]>
}

/**
 * Search options for global find operations.
 */
export interface GlobalFindOptions {
  /** Whether the search is case-sensitive */
  caseSensitive: boolean
  /** Whether to match exact words only */
  exactMatch: boolean
  /** Whether the query is a regular expression */
  regexMode: boolean
}

/**
 * A match result from a global find operation.
 */
export interface GlobalFindMatch {
  /** The URI of the file containing the match */
  uri: UnifiedUri
  /** 1-based line number of the match */
  line: number
  /** 1-based column of the match */
  column: number
  /** The matching text */
  matchText: string
  /** Context around the match (e.g., the full line) */
  context: string
}

/**
 * Provides global find functionality across the workspace.
 */
export interface GlobalFindProvider {
  /**
   * Performs a global find operation across the workspace.
   *
   * @param query - The search query
   * @param options - Search options (case sensitivity, exact match, regex mode)
   * @returns Array of matches found
   */
  globalFind(
    query: string,
    options: GlobalFindOptions,
  ): Promise<GlobalFindMatch[]>

  /**
   * Performs a global replace operation across the workspace.
   * The query and options are decoded from the ID generated by globalFind.
   *
   * @param query - The search query (decoded from the ID)
   * @param replaceWith - The replacement text
   * @param options - Search options (decoded from the ID)
   * @returns The number of replacements made
   */
  globalReplace(
    query: string,
    replaceWith: string,
    options: GlobalFindOptions,
  ): Promise<number>
}

// ============================================================================
// Composite IDE Capabilities
// ============================================================================

/**
 * Callback that gets invoked when diagnostics change.
 * Used for MCP resource subscription support.
 */
export type OnDiagnosticsChangedCallback = (uri: UnifiedUri) => void

/**
 * The complete set of capabilities that an IDE plugin can provide.
 * The SDK will automatically register tools based on which providers are defined.
 */
export interface IdeCapabilities {
  /** Mandatory: Provides file system access for reading files from disk */
  fileAccess: FileAccessProvider

  /** Optional: Provides user interaction for edit operations */
  userInteraction?: UserInteractionProvider

  /** Optional: Provides go-to-definition functionality */
  definition?: DefinitionProvider

  /** Optional: Provides find-references functionality */
  references?: ReferencesProvider

  /** Optional: Provides call hierarchy functionality */
  hierarchy?: HierarchyProvider

  /** Optional: Provides diagnostics for files */
  diagnostics?: DiagnosticsProvider

  /** Optional: Provides document outline (symbols) for files */
  outline?: OutlineProvider

  /** Optional: Provides filesystem access with git-ignore support */
  filesystem?: FilesystemProvider

  /** Optional: Provides global find and replace functionality */
  globalFind?: GlobalFindProvider

  /**
   * Optional: Called by the driver to register a callback for diagnostics changes.
   * When this is provided, the diagnostics resources become subscribable.
   * The plugin should call the registered callback whenever diagnostics change for a URI.
   *
   * @param callback - The callback to invoke when diagnostics change
   */
  onDiagnosticsChanged?: (callback: OnDiagnosticsChangedCallback) => void
}
